[custom]
clash_rule_base=https://raw.githubusercontent.com/reynardli/openclash/refs/heads/main/base.yaml

;1、域名组
domain,proactivebackend-pa.googleapis.com,👽 AI
domain,notifications-pa.googleapis.com,👽 AI
domain-suffix,googleapis.cn,👽 AI
domain-suffix,xn--ngstr-lra8j.com,👽 AI
domain-suffix,services.googleapis.cn,👽 AI
domain-suffix,connectivitycheck.gstatic.com,👽 AI
ruleset=👽 AI,https://raw.githubusercontent.com/reynardli/openclash/refs/heads/main/AI.list
ruleset=👽 AI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.list
ruleset=📘 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
; --- 新增 Google 规则，防止 Gemini 依赖缺失 ---
ruleset=🇬 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.list
; --- 新增 Microsoft 规则，优化办公体验 ---
ruleset=Ⓜ️ Microsoft,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
; -------------------------------------------
ruleset=👯‍♂️ TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=🙋 Telegram,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.list
ruleset=📀 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.list
ruleset=📀 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=📀 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.list
ruleset=📀 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.list
ruleset=🌍 国外,https://raw.githubusercontent.com/reynardli/openclash/refs/heads/main/Proxy.list
ruleset=🌍 国外,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list
ruleset=➡️ 国内,[]FINAL

;2、策略组（域名组-节点组）
custom_proxy_group=👽 AI`select`[]DIRECT`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]REJECT`[]🚀 手动切换
custom_proxy_group=📘 GitHub`select`[]DIRECT`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]REJECT`[]🚀 手动切换
custom_proxy_group=👯‍♂️ TikTok`select`[]DIRECT`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]REJECT`[]🚀 手动切换
custom_proxy_group=🙋 Telegram`select`[]DIRECT`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]REJECT`[]🚀 手动切换
custom_proxy_group=📀 流媒体`select`[]DIRECT`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]REJECT`[]🚀 手动切换
custom_proxy_group=🇬 Google`select`[]DIRECT`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]REJECT`[]🚀 手动切换
custom_proxy_group=Ⓜ️ Microsoft`select`[]DIRECT`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]REJECT`[]🚀 手动切换
custom_proxy_group=🌍 国外`select`[]DIRECT`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]REJECT`[]🚀 手动切换
custom_proxy_group=➡️ 国内`select`[]DIRECT`[]所有-自动`[]港台日新韩-自动`[]台日新韩-自动`[]香港-自动`[]台湾-自动`[]日本-自动`[]新加坡-自动`[]韩国-自动`[]美国-自动`[]其他-自动`[]REJECT`[]🚀 手动切换

;3、节点组
; 将测速地址改为了 Cloudflare，更容易变绿
custom_proxy_group=所有-自动`url-test`.*`http://cp.cloudflare.com/generate_204`300,30
custom_proxy_group=港台日新韩-自动`url-test`(广港|广台|广日|广新|广韩|广美|香港|HK|Hong Kong|🇭🇰|HongKong|台湾|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Tai||日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan|新加坡|SG|坡|狮城|🇸🇬|Singapore|韩国|KR|首尔|春川|🇰🇷|Korea)`http://cp.cloudflare.com/generate_204`300,30
custom_proxy_group=台日新韩-自动`url-test`(广台|广日|广新|广韩|广美|台湾|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Tai|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan|新加坡|SG|坡|狮城|🇸🇬|Singapore|韩国|KR|首尔|春川|🇰🇷|Korea)`http://cp.cloudflare.com/generate_204`300,30
custom_proxy_group=香港-自动`url-test`(广港|香港|HK|Hong Kong|🇭🇰|HongKong)`http://cp.cloudflare.com/generate_204`300,30
custom_proxy_group=台湾-自动`url-test`(广台|台湾|TW|Tai Wan|🇹🇼|🇨🇳|TaiWan|Tai)`http://cp.cloudflare.com/generate_204`300,30
custom_proxy_group=日本-自动`url-test`(广日|日本|JP|川日|东京|大阪|泉日|埼玉|沪日|深日|🇯🇵|Japan)`http://cp.cloudflare.com/generate_204`300,30
custom_proxy_group=新加坡-自动`url-test`(广新|新加坡|SG|坡|狮城|🇸🇬|Singapore)`http://cp.cloudflare.com/generate_204`300,30
custom_proxy_group=韩国-自动`url-test`(广韩|韩国|KR|首尔|春川|🇰🇷|Korea)`http://cp.cloudflare.com/generate_204`300,30
custom_proxy_group=美国-自动`url-test`(广美|美|US|纽约|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|🇺🇸|United States)`http://cp.cloudflare.com/generate_204`300,30
custom_proxy_group=其他-自动`url-test`(阿根廷|AR|Argentina|奥地利|AT|Austria|澳大利亚|AU|Australia|巴西|BR|Brazil|加拿大|CA|Canada|瑞士|CH|Switzerland|德国|DE|Germany|芬兰|FI|Finland|法国|FR|France|英国|UK|GB|United Kingdom|Great Britain|England|印度|IN|India|印尼|ID|Indonesia|爱尔兰|IE|Ireland|意大利|IT|Italy|马来西亚|MY|Malaysia|荷兰|NL|Netherlands|菲律宾|PH|Philippines|俄罗斯|RU|Russia|泰国|TH|Thailand|土耳其|TR|Turkey|越南|VN|Vietnam|南非|ZA|South Africa|墨西哥|MX|Mexico|柬埔寨|KH|Cambodia|尼泊尔|NP|Nepal|乌克兰|UA|Ukraine|西班牙|ES|Spain|葡萄牙|PT|Portugal|瑞典|SE|Sweden|挪威|NO|Norway|丹麦|DK|Denmark|比利时|BE|Belgium|匈牙利|HU|Hungary|波兰|PL|Poland|希腊|GR|Greece|以色列|IL|Israel|阿联酋|AE|UAE|United Arab Emirates|Dubai|沙特|SA|Saudi Arabia|智利|CL|Chile|新西兰|NZ|New Zealand|秘鲁|PE|Peru|缅甸|MM|Myanmar|老挝|LA|Laos)`http://cp.cloudflare.com/generate_204`300,30
custom_proxy_group=🚀 手动切换`select`.*

;4、启用规则集
enable_rule_generator=false
overwrite_original_rules=true




